### PR TITLE
Architecture change

### PR DESCRIPTION
**Pull request by Khalidtoak**
Switched Architecture to MVVM, used coroutines to add contacts so adding contacts now happen in a background thread, Use of Kodeine for dependency Injection, Migration of project to androidX and conversion of the codebase to kotlin. 😊

### CODE REVIEW

**Comment by Lekky71** [comment]
Do not commit the .idea folder.

**Comment by Khalidtoak** [comment]
yeah, I'll delete those

**Comment by Lekky71** [comment]
Great code!! Nice and clean architecture too.
Only one issue, the FAB at the bottom left does not work as expected.
Kindly look into it.

**Comment by Lekky71** [comment]
Everything works well now, great!

**Pull request merged**
